live_config_reload = true

import = [
    "~/.config/alacritty/kanagawa_dragon.toml",
    "~/.config/alacritty/keybindings.toml",
]

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.25

[font.bold]
family = "ZedMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ZedMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ZedMono Nerd Font"
style = "Italic"

[font.normal]
family = "ZedMono Nerd Font"
style = "Regular"


[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/bash"

[window]
dynamic_title = true
opacity = 1.0
startup_mode = "Fullscreen"

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
