[general]
live_config_reload = true
import = [ "~/.config/alacritty/themes/gruvbox-dark-hard.toml" ]

[window]
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
normal = { family = "IosevkaTerm Nerd Font" }
size = 12.0

[colors]
draw_bold_text_with_bright_colors = true

[mouse]
hide_when_typing = true
