format = "$all"
add_newline = false
continuation_prompt = '▶▶ '

[c]
symbol = " "

[directory]
read_only = " 󰌾"

[git_branch]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[rust]
symbol = " "
