format = """
$directory\
$git_branch\
$git_status\
$conda\
$cmd_duration\
$line_break\
$character"""

[directory]
read_only = " 󰌾"
read_only_style = "red"
truncate_to_repo = true
style = "blue"

[git_branch]
format = "([$branch]($style))"
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '
style = "purple"

[cmd_duration]
format = "took [$duration]($style) "
style = "cyan"

[conda]
format = '([\[$symbol$environment\]]($style)) '
style = "bright-black"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
