format = """
$directory\
$git_branch\
$git_status\
$conda\
$cmd_duration\
$line_break\
$character"""

[directory]
read_only = " 󰌾"
read_only_style = "red"
truncate_to_repo = false
style = "blue"

[git_branch]
style = "bright-black"
format = "([$branch]($style))"

[git_status]
style = "purple"
format = '([\[$all_status$ahead_behind\]]($style)) '

[cmd_duration]
style = "cyan"
format = "took [$duration]($style) "

[conda]
symbol = "󰯲 "
style = "bright-black"
format = '([\[$symbol$environment\]]($style)) '

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
