font=IosevkaTerm Nerd Font:size 12
icons-enabled=no
match-counter=yes
list-executables-in-path=yes

[colors]
background=1d2021ff
text=ebdbb2ff
message=83a598ff
prompt=83a598ff
match=fb4934ff
input=ebdbb2ff
selection=ebdbb2ff
selection-text=282828ff
selection-match=fb4934ff
# selection-match=#cb4b16
counter=a89984ff
border=a89984ff
