format = """
$jobs\
$directory\
$git_branch\
$git_status\
$python\
$cmd_duration\
$line_break\
$character"""

[jobs]
number_threshold = 1
format = '[\[$number\]]($style) '
style = "bright-black"

[directory]
read_only = " "
truncate_to_repo = true
fish_style_pwd_dir_length = 1
style = "bright-cyan"

[character]
success_symbol = "[󰘧](bold green)"
error_symbol = "[󰘧](bold red)"

[git_branch]
format = '[$branch]($style)'
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind $stashed)]($style) "
style = "218"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[python]
format ='[(\($virtualenv\))]($style) '
style = "bold white"

[cmd_duration]
format = "[took $duration]($style) "
style = "bright-white"
