#!/usr/bin/env bash

# Thresholds from environment variables
T_WARN="${T_WARN:-70}"
T_CRIT="${T_CRIT:-90}"

# default values
gpu_usage=-1
gpu_mem=-1

# Get GPU usage from radeontop
amd_info=$(radeontop -d - -l 1 2>/dev/null)
if [[ "$amd_info" =~ gpu\ ([0-9]+)\.[0-9]+%.*vram\ ([0-9]+)\.[0-9]+% ]]; then
    gpu_usage="${BASH_REMATCH[1]}"
    gpu_mem="${BASH_REMATCH[2]}"
fi

if [[ "$gpu_usage" == -1 ]]; then
    echo "Can't find GPU information" >&2
    exit 1
fi

# Print full_text, short_text
full_text=$(printf "%.0f%% %.0f%%\n" "$gpu_usage" "$gpu_mem")
echo "$full_text"
printf "%.0f%%\n" "$gpu_usage"

# Print color, if needed
if ((gpu_usage >= T_CRIT || gpu_mem >= T_CRIT)); then
    echo "#FF0000"
elif ((gpu_usage >= T_WARN || gpu_mem >= T_WARN)); then
    echo "#FFBF00"
fi

exit 0
