#!/usr/bin/env bash

yt_music='/usr/bin/chromium --enable-features=UseOzonePlatform --enable-gpu --ozone-platform=wayland --app=https://music.youtube.com'

swaymsg "exec ${yt_music}" && sleep 1 && swaymsg '[app_id="chrome-music.youtube.com__-Default"] move scratchpad'
